[meta]
name = "Map Info"
author = "MisfitMaid, XertroV"
category = "Overlay"
version = "0.5.6"
siteid = 320

[script]
dependencies = ["NadeoServices"]
optional_dependencies = ["ManiaExchange", "ChampionMedals"]
exports = ["ExportFunc.as"]
shared_exports = ["ExportShared.as"]
#__DEFINES__
module = "MapInfo"
