[meta]
name = "Map Info"
author = "MisfitMaid, XertroV"
category = "Overlay"
version = "0.5.9"
siteid = 320

[script]
dependencies = ["NadeoServices"]
optional_dependencies = ["ManiaExchange", "ChampionMedals", "WarriorMedals"]
exports = ["src/ExportFunc.as"]
shared_exports = ["src/ExportShared.as"]
#__DEFINES__
module = "MapInfo"
