[meta]
name = "Map Info"
author = "MisfitMaid, XertroV"
category = "Overlay"
version = "0.3.0"
siteid = 320

[script]
dependencies = ["NadeoServices"]
optional_dependencies = ["ManiaExchange"]
#__DEFINES__
